<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\NapiMunkaeroIgeny;

class CreateNapiMunkaeroIgenyTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('napimunkaeroigeny', function (Blueprint $table) {
            $table->increments('napim_azonosito');
            $table->date('datum');
            $table->unsignedtinyInteger('muszakelo_azon');
            $table->string('munkakor',50);
            $table->unsignedTinyInteger('db')->default(0);
            $table->unique(['datum', 'muszakelo_azon', 'munkakor']);
            $table->foreign('datum')->references('nap')->on('napok')->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('muszakelo_azon')->references('muszakelo_azon')->on('muszakeloszlas')->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('munkakor')->references('megnevezes')->on('munkakor')->onDelete('restrict')->onUpdate('restrict');
            
        });

        NapiMunkaeroIgeny::create(['napim_azonosito' => '1', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '2', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '3', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '4', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '5', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '6', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '7', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '8', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '9', 'datum' => '2022.01.10', 'muszakelo_azon' => '1', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '10', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '11', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '12', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '13', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '14', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '15', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '16', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '17', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '18', 'datum' => '2022.01.10', 'muszakelo_azon' => '2', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '19', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '20', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '21', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '22', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '23', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '24', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '25', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '26', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '27', 'datum' => '2022.01.10', 'muszakelo_azon' => '3', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '28', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Felszolgáló', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '29', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Konyhai kisegítő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '30', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Leszedő', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '31', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '32', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '33', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '34', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '35', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '36', 'datum' => '2022.01.10', 'muszakelo_azon' => '4', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '37', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '38', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '39', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '40', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '41', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '42', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '43', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '44', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '45', 'datum' => '2022.01.10', 'muszakelo_azon' => '5', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '46', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '47', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '48', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '49', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '50', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '51', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '52', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '53', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '54', 'datum' => '2022.01.10', 'muszakelo_azon' => '6', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '55', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '56', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '57', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '58', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '59', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '60', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '61', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '62', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '63', 'datum' => '2022.01.10', 'muszakelo_azon' => '7', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '64', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '65', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '66', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '67', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '68', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '69', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '70', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '71', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Takarító', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '72', 'datum' => '2022.01.10', 'muszakelo_azon' => '8', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '73', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '74', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '75', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '76', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '77', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '78', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '79', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '80', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '81', 'datum' => '2022.01.11', 'muszakelo_azon' => '1', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '82', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '83', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '84', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '85', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '86', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '87', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '88', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '89', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '90', 'datum' => '2022.01.11', 'muszakelo_azon' => '2', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '91', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '92', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '93', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '94', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '95', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '96', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '97', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '98', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '99', 'datum' => '2022.01.11', 'muszakelo_azon' => '3', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '100', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Felszolgáló', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '101', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Konyhai kisegítő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '102', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Leszedő', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '103', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '104', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '105', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '106', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '107', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '108', 'datum' => '2022.01.11', 'muszakelo_azon' => '4', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '109', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '110', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '111', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '112', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '113', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '114', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '115', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '116', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '117', 'datum' => '2022.01.11', 'muszakelo_azon' => '5', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '118', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '119', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '120', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '121', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '122', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '123', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '124', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '125', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '126', 'datum' => '2022.01.11', 'muszakelo_azon' => '6', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '127', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '128', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '129', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '130', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '131', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '132', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '133', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '134', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '135', 'datum' => '2022.01.11', 'muszakelo_azon' => '7', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '136', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '137', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '138', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '139', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '140', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '141', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '142', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '143', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Takarító', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '144', 'datum' => '2022.01.11', 'muszakelo_azon' => '8', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '145', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '146', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '147', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '148', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '149', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '150', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '151', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '152', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '153', 'datum' => '2022.01.12', 'muszakelo_azon' => '1', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '154', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '155', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '156', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '157', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '158', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '159', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '160', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '161', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '162', 'datum' => '2022.01.12', 'muszakelo_azon' => '2', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '163', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '164', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '165', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '166', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '167', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '168', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '169', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '170', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '171', 'datum' => '2022.01.12', 'muszakelo_azon' => '3', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '172', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Felszolgáló', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '173', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Konyhai kisegítő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '174', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Leszedő', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '175', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '176', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '177', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '178', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '179', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '180', 'datum' => '2022.01.12', 'muszakelo_azon' => '4', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '181', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '182', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '183', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '184', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '185', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '186', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '187', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '188', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '189', 'datum' => '2022.01.12', 'muszakelo_azon' => '5', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '190', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '191', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '192', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '193', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '194', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '195', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '196', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '197', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '198', 'datum' => '2022.01.12', 'muszakelo_azon' => '6', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '199', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '200', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '201', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '202', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '203', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '204', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '205', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '206', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '207', 'datum' => '2022.01.12', 'muszakelo_azon' => '7', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '208', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '209', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '210', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '211', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '212', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '213', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '214', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '215', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Takarító', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '216', 'datum' => '2022.01.12', 'muszakelo_azon' => '8', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '217', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '218', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '219', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '220', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '221', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '222', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '223', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '224', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '225', 'datum' => '2022.01.13', 'muszakelo_azon' => '1', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '226', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '227', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '228', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '229', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '230', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '231', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '232', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '233', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '234', 'datum' => '2022.01.13', 'muszakelo_azon' => '2', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '235', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '236', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '237', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '238', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '239', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '240', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '241', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '242', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '243', 'datum' => '2022.01.13', 'muszakelo_azon' => '3', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '244', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Felszolgáló', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '245', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Konyhai kisegítő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '246', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Leszedő', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '247', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '248', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '249', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '250', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '251', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '252', 'datum' => '2022.01.13', 'muszakelo_azon' => '4', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '253', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '254', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '255', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '256', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '257', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '258', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '259', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '260', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '261', 'datum' => '2022.01.13', 'muszakelo_azon' => '5', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '262', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '263', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '264', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '265', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '266', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '267', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '268', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '269', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '270', 'datum' => '2022.01.13', 'muszakelo_azon' => '6', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '271', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '272', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '273', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '274', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '275', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '276', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '277', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '278', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '279', 'datum' => '2022.01.13', 'muszakelo_azon' => '7', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '280', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '281', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '282', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '283', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '284', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '285', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '286', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '287', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Takarító', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '288', 'datum' => '2022.01.13', 'muszakelo_azon' => '8', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '289', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '290', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '291', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '292', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '293', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '294', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '295', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '296', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '297', 'datum' => '2022.01.14', 'muszakelo_azon' => '1', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '298', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '299', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '300', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '301', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '302', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '303', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '304', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '305', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '306', 'datum' => '2022.01.14', 'muszakelo_azon' => '2', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '307', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '308', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '309', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '310', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '311', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '312', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Szakács', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '313', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '314', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '315', 'datum' => '2022.01.14', 'muszakelo_azon' => '3', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '316', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Felszolgáló', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '317', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Konyhai kisegítő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '318', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Leszedő', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '319', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '320', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '321', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '322', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '323', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '324', 'datum' => '2022.01.14', 'muszakelo_azon' => '4', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '325', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '326', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '327', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '328', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '329', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '330', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '331', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '332', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '333', 'datum' => '2022.01.14', 'muszakelo_azon' => '5', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '334', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '335', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '336', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '337', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '338', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '339', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '340', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Szakácssegéd', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '341', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '342', 'datum' => '2022.01.14', 'muszakelo_azon' => '6', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '343', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '344', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '345', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '346', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Pultos', 'db' => '3']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '347', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '348', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '349', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '350', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '351', 'datum' => '2022.01.14', 'muszakelo_azon' => '7', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '352', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '353', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '354', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '355', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '356', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '357', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '358', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '359', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Takarító', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '360', 'datum' => '2022.01.14', 'muszakelo_azon' => '8', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '361', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '362', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '363', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '364', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '365', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '366', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '367', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '368', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '369', 'datum' => '2022.01.15', 'muszakelo_azon' => '9', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '370', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '371', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '372', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '373', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Pultos', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '374', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '375', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '376', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '377', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '378', 'datum' => '2022.01.15', 'muszakelo_azon' => '10', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '379', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '380', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '381', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '382', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '383', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '384', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '385', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '386', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '387', 'datum' => '2022.01.15', 'muszakelo_azon' => '11', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '388', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '389', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Konyhai kisegítő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '390', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '391', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '392', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '393', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '394', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '395', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '396', 'datum' => '2022.01.15', 'muszakelo_azon' => '12', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '397', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '398', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '399', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '400', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '401', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '402', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '403', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '404', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '405', 'datum' => '2022.01.15', 'muszakelo_azon' => '13', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '406', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '407', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '408', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '409', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '410', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '411', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '412', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '413', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Takarító', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '414', 'datum' => '2022.01.15', 'muszakelo_azon' => '14', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '415', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '416', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '417', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '418', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '419', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '420', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '421', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '422', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '423', 'datum' => '2022.01.16', 'muszakelo_azon' => '9', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '424', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '425', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '426', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '427', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Pultos', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '428', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '429', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '430', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '431', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '432', 'datum' => '2022.01.16', 'muszakelo_azon' => '10', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '433', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '434', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '435', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '436', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '437', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '438', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '439', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '440', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '441', 'datum' => '2022.01.16', 'muszakelo_azon' => '11', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '442', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '443', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Konyhai kisegítő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '444', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '445', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '446', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '447', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '448', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '449', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '450', 'datum' => '2022.01.16', 'muszakelo_azon' => '12', 'munkakor' => 'Üzletvezető', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '451', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '452', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '453', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '454', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '455', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '456', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Szakács', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '457', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Szakácssegéd', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '458', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '459', 'datum' => '2022.01.16', 'muszakelo_azon' => '13', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '460', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Felszolgáló', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '461', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Konyhai kisegítő', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '462', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Leszedő', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '463', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Pultos', 'db' => '2']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '464', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Sommelier', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '465', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '466', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '467', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Takarító', 'db' => '1']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '468', 'datum' => '2022.01.16', 'muszakelo_azon' => '14', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '469', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '470', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '471', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '472', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '473', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '474', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '475', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '476', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Felszolgáló', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '477', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '478', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '479', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '480', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '481', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '482', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '483', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '484', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Konyhai kisegítő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '485', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '486', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '487', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '488', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '489', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '490', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '491', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '492', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Leszedő', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '493', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '494', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '495', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '496', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '497', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '498', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '499', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '500', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Pultos', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '501', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '502', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '503', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '504', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '505', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '506', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '507', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '508', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Sommelier', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '509', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '510', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '511', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '512', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '513', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '514', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '515', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '516', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Szakács', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '517', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '518', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '519', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '520', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '521', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '522', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '523', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '524', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Szakácssegéd', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '525', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '526', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '527', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '528', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '529', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '530', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '531', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '532', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Takarító', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '533', 'datum' => '2022.02.20', 'muszakelo_azon' => '1', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '534', 'datum' => '2022.02.20', 'muszakelo_azon' => '2', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '535', 'datum' => '2022.02.20', 'muszakelo_azon' => '3', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '536', 'datum' => '2022.02.20', 'muszakelo_azon' => '4', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '537', 'datum' => '2022.02.20', 'muszakelo_azon' => '5', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '538', 'datum' => '2022.02.20', 'muszakelo_azon' => '6', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '539', 'datum' => '2022.02.20', 'muszakelo_azon' => '7', 'munkakor' => 'Üzletvezető', 'db' => '0']);
        NapiMunkaeroIgeny::create(['napim_azonosito' => '540', 'datum' => '2022.02.20', 'muszakelo_azon' => '8', 'munkakor' => 'Üzletvezető', 'db' => '0']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('napimunkaeroigeny');
    }
}
